version: '3.8'

services:
  # 1. Servicio del Agente 
  agent:
    build:
      context: ./ctm-investment-agent
      dockerfile: Dockerfile
    container_name: langgraph-agent
    env_file:
      - .env  
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # 2. Servicio de Base de Datos (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: langgraph-db
    env_file:
      - .env 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"] 
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # 3. Servicio de Cache/Cola (Redis)
  redis:
    image: redis:7-alpine
    container_name: langgraph-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # 4. Servicio de Admin de BD (PgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: langgraph-pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  pgadmin_data: